services:
  identity-service:
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
    image: quay.io/keycloak/keycloak:24.0.1
    ports:
      - 8090:8080
    command: -v start-dev --import-realm
    volumes:
      - ./docs/keycloak:/opt/keycloak/data/import
    restart: unless-stopped
  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
